[package]
name = "pipeline-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
fs-utils = "1.1.4"
glob = "0.3.3"
serde_yml = "0.0.12"
subprocess = "0.2.9"
thiserror = "2.0.17"
tokio = { version = "1", features = ["full"] }

